services:
  weather_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_SOURCE_URL=jdbc:h2:mem:testdb
      - OPENWEATHER_API_KEY=
      - SPRING_H2_CONSOLE_ENABLED=true